### ISSUE TITLE
router.py error

### ISSUE THREAD

**Issue by stephaniec2020** [FinMind/FinMindBook#4]
### Environment Information

- **Operating System:** MacOS Version 13.6.3
- **Python Version:** 3.7

您好，最近在依照著書上的指引 而嘗試導入sql而terminal彈出以下error message:
```shell
pipenv run python financialdata/twse_crawler.py 2024-01-02 2024-01-04 
```
已經根據最新pull request更改url，可以獲取csv但sql並不成功 
error message:
```shell                                                                                                 
2024-02-24 19:39:48.504 | INFO     | __main__:main:215 - Script started.
  0%|                                                                                                                                                  | 0/3 [00:00<?, ?it/s]2024-02-24 19:39:48.519 | INFO     | __main__:main:217 - 2024-01-02
2024-02-24 19:40:00.478 | ERROR    | financialdata.router:check_connect_alive:26 - get_mysql_financialdata_conn connect, error: Not an executable object: 'SELECT 1 + 1'
2024-02-24 19:40:05.487 | ERROR    | financialdata.router:check_connect_alive:26 - get_mysql_financialdata_conn connect, error: Not an executable object: 'SELECT 1 + 1'
  0%|                                                                                                                                                  | 0/3 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/Users/<username>/.local/share/virtualenvs/finmind-U98f56oP/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1404, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/<username>/Documents/finmind/financialdata/router.py", line 23, in check_connect_alive
    check_alive(connect)
  File "/Users/<username>/Documents/finmind/financialdata/router.py", line 9, in check_alive
    connect.execute("SELECT 1 + 1")
  File "/Users/<username>/.local/share/virtualenvs/finmind-U98f56oP/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1406, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'SELECT 1 + 1'
```
敬請各位，可以看此error message 而指點一下嗎？

**Comment by stephaniec2020** [comment]
感謝 @linsamtw 解決問題，更新pipfile python_version和venv至python3.10解決
